name: chat
description: Simple chat app by Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  google_sign_in: ^5.3.3
  cloud_firestore: ^3.1.18
  intl: ^0.17.0
  fake_cloud_firestore: ^1.3.0
  flutter_riverpod: ^1.0.4
  google_sign_in_mocks:
    git:
      url: https://github.com/kenta-wakasa/google_sign_in_mocks
  firebase_auth_mocks: ^0.8.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
